### ISSUE TITLE
Allow public access

### ISSUE THREAD

**Issue by ncasnap** [openfun/jitsi-magnify#185]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
At the moment as soon as we create a meeting, this meeting is private. If you are not in the member list and registered to magnify you cannot join the meeting. This is great for VIP but in some cases we need to invite people from outside to join as guest via magnify but we have this :
![image](https://user-images.githubusercontent.com/107538862/233382152-f81c5033-3c8c-4a16-8c8e-bd64649c3662.png)

**Describe the solution you'd like**
What we would like is to get the possibility to make the room private or public. That way a public meeting can also be protected with a password etc..

Here is some ideas : 
when it is public
![image](https://user-images.githubusercontent.com/107538862/233382551-203ae5c2-edef-454d-abc6-2dc211d1d404.png)

When it is private

![image](https://user-images.githubusercontent.com/107538862/233382894-15bda9f1-5a16-4293-afad-fe897012bda0.png)

What do you think about the feature ?
I stay available if you need more information.
Regards,
Nathan

**Comment by sampaccoud** [comment]
Do we agree that when you write "meeting" we should read "room"? Meetings are another object in Magnify. Just to make sure.
If yes, there is already a field "is_public" on the room so it is our mistake that we fogot to expose it on the UX.

**Comment by Moustique82** [comment]
Yes, it s for room :-)
We are very interested in displaying this parameters on the front.

**Comment by Moustique82** [comment]
by default, it would be better to be public

**Comment by ncasnap** [comment]
Hello,

We talked about the button and it could be better for the user experience to display it in the security part.

We stay available if needed.
Regards,
Nathan
