### ISSUE TITLE
French Language home page

### ISSUE THREAD

**Issue by ncasnap** [openfun/jitsi-magnify#197]
## Bug Report

**Problematic behavior**
When a user go to home page for the 1st time. The page is in english even if the language is configured in French in the configuration.
![image](https://github.com/openfun/jitsi-magnify/assets/107538862/96416e5f-6796-4962-95d3-c47b6109013d)

As soon as I login, the interface is changed in French as configured in our settings.py. 
And then when I logout the home page is now in French.

The issue remains when it is the first time we access magnify.

**Expected behavior/code**
We expect to get the home page in the language configured in settings.py even before login for the first time.

**Steps to Reproduce**
1. Configure magnify for French by default
2. Use private navigation
3. access magnify home page=> It should appear in english
4. Login => It should appear in french
5. logout to home page => The home page is now in french

**Environment**
- Jitsi magnify version:
- Platform:

I stay available if you need more information.
Regards
Nathan

**Comment by PanchoutNathan** [comment]
We are already fixing this problem in another ongoing PR. Thx for the help :)

**Comment by ncasnap** [comment]
Thank you for the feedback !

**Comment by ncasnap** [comment]
Can you give the PR number, that way we can follow the resolution of this issue please ?
