### ISSUE TITLE
Extra padding on illustration section

### ISSUE THREAD

**Issue by jbpenrath** [openfun/jitsi-magnify#213]
## Bug Report

**Problematic behavior**
On desktop, the page is vertically divided in two section. An illustration section then the content section.

Currently the illustration section has a padding of 2rem all around so the illustration used does not stick on edges that look visually weird.

**Expected behavior/code**
The illustration section should not have padding in order to stick illustration on left and bottom edges.

**Possible Solution**
1. Remove the `padding: 2rem` to the illustration box component.
2. Display the illustration through CSS with `background-image` and keep only the FUN Logo as image. From my point of view, this solution is more semantically adapted.

**Additional context/Screenshots**
<img width="701" alt="image" src="https://github.com/openfun/jitsi-magnify/assets/9265241/9a206d53-9ee4-4adf-9ad8-bdbe31d6aca6">

**Comment by Moustique82** [comment]
Hi JB, Link this issues : https://github.com/openfun/jitsi-magnify/issues/182 ?
