### ISSUE TITLE
Create routes on the back end to manage groups 

### ISSUE THREAD

**Issue by DarkPitoune** [openfun/jitsi-magnify#24]
## Feature Request

The front end includes buttons that don't do anything, which is not a good thing :(

**Describe the solution you'd like**
We should code routes to : 
- get the members and infos of a given group
- create a group, given a list of people identified by their email
- delete a group
- rename a group
- add someone to a group, given an email
- remove someone from a group, given an email

**Do you want to work on it through a Pull Request?**
I might..

**Comment by DarkPitoune** [comment]
Please feel free to comment new methods I didn't think of

**Comment by Leonils** [comment]
Solved by #47
