### ISSUE TITLE
implement auth

### ISSUE THREAD

**Issue by DarkPitoune** [openfun/jitsi-magnify#25]
## Feature Request

It would be nice if people could connect to their account to access to routes depending on what they are allowed to see and do

**Describe the solution you'd like**
Well django packages auth pretty nively, let's use it !

**Discovery, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs (if applicable).
Maybe a screenshot or design?

**Do you want to work on it through a Pull Request?**
If you ask so nicely ;)

**Comment by Leonils** [comment]
Solved by #46
