### ISSUE TITLE
Dev scripts to help development

### ISSUE THREAD

**Issue by AlexLaval** [openfun/jitsi-magnify#28]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
When creating frontend components for example, a huge part of the code is very similar from one component to another. Finding a way to automate folder and files creation could be useful.

**Describe the solution you'd like**
Some scripts, for example in `src/frontend/scripts/`, that can be executed to add components.

**Describe alternatives you've considered**
Keeping on doing it by hand, but it's not very convenient.

**Discovery, Documentation, Adoption, Migration Strategy**
You should be able, in `src/frontend` folder, to execute a script like `yarn add-icon` that could give you all necessary files in the right place in the `magnify` folder, and updates export references and stories.

**Do you want to work on it through a Pull Request?**
Yes.

**Comment by sampaccoud** [comment]
:medal_sports: @AlexLaval lazy devs are the best! :smile:
