### ISSUE TITLE
Overlapping in MeetingRow at big text sizes

### ISSUE THREAD

**Issue by asynkr** [openfun/jitsi-magnify#85]
## Bug Report

**Problematic behavior**
Increasing text size in `MeetingRow` make the "Join" button and the meeting name overlap, even if there is still enough space for both (see screenshots).
The problem may appear sooner with long meeting names

**Expected behavior/code**
No overlapping

**Steps to Reproduce**
See the storybook !

**Additional context/Screenshots**
![row1](https://user-images.githubusercontent.com/102617193/178746882-8e7e504d-1a5d-4747-b37b-f5431c904fef.PNG)
![row2](https://user-images.githubusercontent.com/102617193/178746892-2621f438-3bf8-481b-989a-939945a43dd9.PNG)
![row3](https://user-images.githubusercontent.com/102617193/178746906-22961a52-f5dc-4ef7-965a-7e26df7a7ce0.PNG)
![row4](https://user-images.githubusercontent.com/102617193/178746914-e31275a6-f703-48ed-ab57-b7e0fc7faeaa.PNG)

**Comment by RaoufCherif** [comment]
Hi,

From what I can see their is no more `MeetingRow` in the repo. I guess it was replaced by `RoomRow`, should we close the issue ?
