### ISSUE TITLE
Auth/SSO features

### ISSUE THREAD

**Issue by asynkr** [openfun/jitsi-magnify#91]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Currently, users are using django auth system. To enable Magnify to be easy to access, even for newcomers, we could add other auth features.

**Describe the solution you'd like**
- Keycloak
- Shibboleth
- Third party auth like Google, Microsoft,...

**Discovery, Documentation, Adoption, Migration Strategy**
To do !

**Comment by sampaccoud** [comment]
We implemented OIDC auth and included a demo with Keycloak in the repo.
